CREATE TABLE user_role (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) REFERENCES app_user(id) ON DELETE CASCADE NOT NULL,
    role_id VARCHAR(36) REFERENCES role(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);