CREATE TABLE app_user (
    id VARCHAR(36) PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    username VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(14),
    birthday DATE,
    country_id VARCHAR(36),
    token_expiration TIMESTAMP,
    token_mail VARCHAR(255),
    access_failed_count INT DEFAULT 0,
    lockout_enabled BOOLEAN DEFAULT FALSE,
    lockout_end TIMESTAMP,
    two_factor_enabled BOOLEAN DEFAULT FALSE,
    refresh_token_enabled BOOLEAN DEFAULT FALSE,
    theme VARCHAR(20),
    profile_pic_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_country FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE SET NULL
);